---
- name: Install NCPA and Register Host and Services
  hosts: all
# remote_user: root
  become: true
  vars_files:
    - 'secrets.yml'
  vars:
    xi_ip: '172.31.27.40'

  roles:
    - role: ncpa_install_linux
    - role: register_with_xi
    - role: xi_apply_config
